"""initial schema

Revision ID: 209f35325d09
Revises: 
Create Date: 2026-08-27 23:10:01.356891
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.crypto

revision = '209f35325d09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('payload', app.crypto.EncryptedJSON(), nullable=True),
    sa.Column('requirements_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=True),
    sa.Column('raw_body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pending', 'processed', 'failed')", name='ck_webhook_events_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_webhook_events_status'), 'webhook_events', ['status'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('draft_id', sa.UUID(), nullable=True),
    sa.Column('request_path', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('request_body', app.crypto.EncryptedJSON(), nullable=True),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('conduit_resource_id', sa.String(length=128), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reconcile_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('in_flight_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unknown_since', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state in ('created', 'in_flight', 'confirmed', 'rejected', 'outcome_unknown', 'abandoned', 'stalled')", name='ck_operations_state'),
    sa.CheckConstraint("type in ('onboarding_submit', 'customer_update', 'feature_request', 'document_upload', 'rfi_respond', 'whitelist_create', 'whitelist_revoke', 'payout_create', 'payout_cancel', 'order_create', 'order_execute', 'order_cancel', 'webhook_endpoint_register')", name='ck_operations_type'),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_state'), 'operations', ['state'], unique=False)
    op.create_index('uq_operations_active_request', 'operations', ['type', 'request_hash'], unique=True, postgresql_where=sa.text("state in ('created', 'in_flight', 'outcome_unknown')"))
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_operation_id'), 'audit_events', ['operation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_operation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('uq_operations_active_request', table_name='operations', postgresql_where=sa.text("state in ('created', 'in_flight', 'outcome_unknown')"))
    op.drop_index(op.f('ix_operations_state'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_webhook_events_status'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_table('drafts')
    # ### end Alembic commands ###
