#!/usr/bin/env python3
"""Generate PERMISSIONS.md from the catalog and the live route table.

    python scripts/generate_permission_matrix.py            # rewrite PERMISSIONS.md
    python scripts/generate_permission_matrix.py --check    # exit 1 if it is stale

The doc a client reads during a security review has to be the enforcement, not a
description of it — so the grid, the descriptions and the "enforced on" lists all
come from `app/permissions.py` and from the app's own routing table.
`tests/test_permissions.py` runs `--check`'s comparison, which is what stops the
two from drifting (same idiom as the pinned OpenAPI snapshot).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from cryptography.fernet import Fernet

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "PERMISSIONS.md"

# Building the app runs the startup guards, which want a config. Nothing here
# connects to anything — no lifespan, no request — so placeholders are enough,
# and a real environment (CI, a container) overrides them. ENCRYPTION_KEY must
# still pass the Fernet-format guard, so it is minted fresh on every run
# rather than a fixed value living in source control.
os.environ.setdefault("DATABASE_URL", "postgresql+psycopg://localhost/unused")
os.environ.setdefault("SESSION_SECRET", "generator-placeholder-not-a-deployment")
os.environ.setdefault("ENCRYPTION_KEY", Fernet.generate_key().decode())
os.environ.setdefault("AUTH_MODE", "disabled")

from app.auth.web import route_gates  # noqa: E402
from app.main import create_app  # noqa: E402
from app.permissions import (  # noqa: E402
    BUILTIN_ROLES,
    PERMISSIONS,
    REQUIRES,
    ROLES,
    VIEW,
    admin_class,
)

PREAMBLE = """# Permission catalog

<!-- Generated by scripts/generate_permission_matrix.py. Do not edit by hand:
     a test compares this file against the catalog and the route table. -->

Every action this console gates has a name. Routes declare a permission; roles
are bundles of permissions. This file is generated from
[`app/permissions.py`](app/permissions.py) and from the app's own routing table,
so it cannot describe a rule the code does not enforce.

> **These names are contract.** They are what a deployment writes in its
> `ROLES_FILE`. A rename here breaks every role file that used the old name, so
> treat one like any other breaking change: add a new name, never re-point an
> existing one at a different action.

## The three built-in roles

`viewer` reads, `operator` moves money, `admin` additionally holds the release
valves — the actions that undo or erase what another operator did. They are
**fixed**: a `ROLES_FILE` that redefines one is refused at startup, so an
upgrade cannot quietly change what an existing role means.
"""

RULES = """
## What is *not* gated by a permission

Six routes carry no permission, on purpose:

| Route | Why |
|---|---|
| `GET /health/live`, `GET /health/ready` | Deployment probes. They must work without credentials, and they answer with a status and nothing else. |
| `POST /webhooks/conduit` | Conduit's delivery, verified by its signature. There is no operator and no session; an operator permission would be meaningless. |
| `GET /auth/login`, `POST /auth/logout` | The sign-in ceremony itself. Every authenticated actor may end their own session. |
| `GET /customers/{customer_id}/counterparties` | A 301 to the renamed Contacts page. It reads nothing and renders nothing. |

Everything else that changes state — every `POST`, `PUT` and `DELETE` in
`app/web` — declares a cataloged permission, and a test walks the route table on
every run to prove it. An action that shipped without a gate would fail the
suite by name.

Reads are one permission, `console.view`: the console has a single read surface,
and every list and detail page in it has always been gated the same way.
Three GETs are named otherwise: `export.csv`, because a download is not a page —
it takes the same PII off the screen and into a file — and the two pages that
*are* the action rather than a view of it, a contact's edit form (`contact.edit`)
and a batch's dispatch confirmation (`batch.dispatch`).

## Custom roles

Set `ROLES_FILE` to a JSON file:

```json
{
  "payments-clerk": ["console.view", "payout.create", "contact.edit"],
  "batch-dispatcher": ["console.view", "batch.dispatch"],
  "reporting": ["console.view", "export.csv"]
}
```

Map your IdP's groups onto those names with `AUTH_ROLE_MAP` exactly as you would
a built-in role (`AUTH_ROLE_MAP=finance-team=payments-clerk`); an unmapped group
still grants nothing. Roles are deployment config, not a runtime screen: they
live in your own change control, where the diff is reviewed before it ships.

The file is read once, at startup, and **the app refuses to start** rather than
run with a role file it cannot honour:

| Refused | Message names |
|---|---|
| A permission that is not in the catalog | the role, the bad name, and the closest real permission |
| A permission without the reads it requires (*Requires*, above) | the role, the permission, and what is missing |
| An admin-class permission without the whole operator base | the role, the permission, and how many operator permissions are missing |
| A role that grants nothing | the role |
| A role that redefines `viewer`, `operator` or `admin` | the role |
| A file that is unreadable or is not JSON | the setting and the parse error |

Admin-class permissions are the release valves — {admin_class} — plus
`sandbox.simulate` anywhere `CONDUIT_ENV` is not `sandbox`, because off the
sandbox host those routes still post to a real one.

## What the screen says

Where a page withholds an action, it names the action and then the permission
that would allow it — *"Read-only: sending a payout needs the `payout.create`
permission."* — in the same vocabulary as this file, so an operator can quote
the sentence to whoever maintains the role file and that person can find the row
above without translating anything.

No sentence names a role. Which role carries a permission is the deployment's
decision, and the console cannot know it: a custom role may hold
`payout.create` without being `operator`, and telling that operator to "ask an
admin" would be a guess about someone else's org chart. A surface that gates
several actions separately names each one's permission, because a role holds
them one at a time.
"""


def matrix(gates) -> str:
    by_permission: dict[str, list[str]] = {name: [] for name in PERMISSIONS}
    for method, path, _endpoint, declared in gates:
        for name in sorted(declared):
            by_permission[name].append(f"{method} {path}")

    out = [PREAMBLE, "## The grid\n"]
    out.append("| Permission | " + " | ".join(ROLES) + " | What it allows |")
    out.append("|---|" + ":-:|" * len(ROLES) + "---|")
    for name, description in PERMISSIONS.items():
        held = " | ".join("✓" if name in BUILTIN_ROLES[r] else "·" for r in ROLES)
        out.append(f"| `{name}` | {held} | {description} |")

    out.append("\n## Where each one is enforced\n")
    for name, description in PERMISSIONS.items():
        needs = sorted(REQUIRES.get(name, ()))
        out.append(f"### `{name}`\n")
        out.append(f"{description}\n")
        out.append(
            "*Requires:* "
            + (", ".join(f"`{n}`" for n in needs) if needs else "nothing — it is the read itself")
            + "  "
        )
        routes = by_permission[name]
        out.append(f"*Held by:* {', '.join(r for r in ROLES if name in BUILTIN_ROLES[r])}  ")
        if routes:
            out.append(f"*Enforced on {len(routes)} route{'' if len(routes) == 1 else 's'}:*\n")
            out += [f"- `{route}`" for route in routes]
        else:
            out.append(
                "*Enforced on no route:* it gates a record, not a URL — "
                "another operator's draft is only readable to someone holding it.\n"
            )
        out.append("")

    out.append(
        RULES.replace(
            "{admin_class}",
            ", ".join(f"`{n}`" for n in sorted(admin_class("sandbox"))),
        )
    )
    return "\n".join(out).rstrip() + "\n"


def generate() -> str:
    return matrix(route_gates(create_app()))


if __name__ == "__main__":
    fresh = generate()
    if "--check" in sys.argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != fresh:
            print(f"{OUTPUT.name} is stale — run scripts/generate_permission_matrix.py")
            sys.exit(1)
        print(f"{OUTPUT.name} is current")
    else:
        OUTPUT.write_text(fresh, encoding="utf-8")
        print(f"wrote {OUTPUT} ({len(PERMISSIONS)} permissions, VIEW={VIEW})")
